language: rust
cache: cargo

env:
  global:
    - NVS_VERSION=1.5.4
    - NODEJS_VERSION=node/13

jobs:
  include:
    - env: RUST_BACKTRACE=1
      script:
        - cargo test

    - addons:
        firefox: latest-esr
        chrome: stable
      env: RUST_BACKTRACE=1
      before_install: # Install npm
        - git clone --branch v$NVS_VERSION --depth 1 https://github.com/jasongin/nvs ~/.nvs
        - . ~/.nvs/nvs.sh
        - nvs --version
        - nvs add $NODEJS_VERSION
        - nvs use $NODEJS_VERSION
        - node --version
        - npm --version
      before_script:
        - rustup target add wasm32-unknown-unknown
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        - npm i
      script:
        - npm run test
        - npm run build:prod
